services:
  - type: web
    name: fittable
    runtime: php
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    buildFilter:
      paths:
        - "**"
    envVars:
      - key: NODE_VERSION
        value: "20.19.0"
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_CACHE_CONNECTION
        value: pgsql
      - key: DB_CACHE_LOCK_CONNECTION
        value: pgsql
      - key: DB_CACHE_LOCK_TABLE
        value: cache_locks
      # Database (NeonDB)
      - key: DB_URL
        sync: false  # Set this manually in Render dashboard with your NeonDB connection string
      # Email (SendGrid)
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.sendgrid.net
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: apikey
      - key: MAIL_PASSWORD
        sync: false  # Set this manually in Render dashboard with your SendGrid API key
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false  # Set to your verified sender email (e.g., noreply@yourdomain.com)
      - key: MAIL_FROM_NAME
        value: Fittable
      # AI Service
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
